### ISSUE TITLE
Question - Planned Feature

### ISSUE THREAD

**Issue by NielsPilgaard** [Buuz135/WorldGen-Indicators#1]
Hey o/ I was wondering if you're still planning to implement the feature `Generate at a define Y relative to the surface` at some point? I'd like to use it :)

**Comment by Buuz135** [comment]
Yes, maybe it will be done for next week

**Comment by NielsPilgaard** [comment]
Awesome!

**Comment by NielsPilgaard** [comment]
Thank you :)

**Comment by NielsPilgaard** [comment]
Does the RelativeSurfaceIndicator not accept negative integers?

**Comment by Buuz135** [comment]
Yes but it currently doesnt replace blocks

**Comment by NielsPilgaard** [comment]
It doesn't seem to be working with any integer, here's the offending line of the script and the error:
https://hastebin.com/muxekojixo.rb

Edit: I forgot to import the RelativeSurfaceChecker. Derp.

**Comment by NielsPilgaard** [comment]
Oh and do you plan on making it able to replace blocks? :)

**Comment by NielsPilgaard** [comment]
It's working perfectly now, and the result is exactly what I had hoped, thank you.
