### ISSUE TITLE
Trees Viewed as Surface

### ISSUE THREAD

**Issue by NielsPilgaard** [Buuz135/WorldGen-Indicators#3]
Hey o/

It would appear that WorldGen Indicators sees trees as groundlevel:
![billede](https://user-images.githubusercontent.com/21295394/49080147-0119d180-f243-11e8-816e-b770952fabfc.png)

Will I need to blacklist leaves, or could this be changed in the mod?

**Comment by Buuz135** [comment]
Yes, you can blacklist leaves, you can use `treeLeaves` OreDictionary to get them all easily.

**Comment by NielsPilgaard** [comment]
Cool, thanks.
